import type {
  IntrospectionData,
  IntrospectionField,
  IntrospectionInputValue,
  IntrospectionSchema,
  IntrospectionType,
  TypeRef,
} from '../introspection';
import type { GraphQLResult, ScopedDataClient } from '../scopedClient';

/**
 * Introspection fixtures for adapter unit tests. Deliberately generic
 * (library-catalog nouns, not any real portal domain — ADR-0002); shaped like
 * a Hippo-style autogenerated read surface: list fields with
 * filter/limit/offset/search args, enum + relationship fields, a batch
 * mutation.
 */

export const scalar = (name: string): TypeRef => ({ kind: 'SCALAR', name, ofType: null });
export const enumRef = (name: string): TypeRef => ({ kind: 'ENUM', name, ofType: null });
export const object = (name: string): TypeRef => ({ kind: 'OBJECT', name, ofType: null });
export const nonNull = (ofType: TypeRef): TypeRef => ({ kind: 'NON_NULL', name: null, ofType });
export const list = (ofType: TypeRef): TypeRef => ({ kind: 'LIST', name: null, ofType });

export const field = (
  name: string,
  type: TypeRef,
  args: IntrospectionInputValue[] = [],
): IntrospectionField => ({ name, args, type });

export const arg = (name: string, type: TypeRef): IntrospectionInputValue => ({ name, type });

export const objectType = (name: string, fields: IntrospectionField[]): IntrospectionType => ({
  kind: 'OBJECT',
  name,
  fields,
});

export const inputObjectType = (
  name: string,
  inputFields: IntrospectionInputValue[],
): IntrospectionType => ({ kind: 'INPUT_OBJECT', name, inputFields });

export const enumType = (name: string, values: string[]): IntrospectionType => ({
  kind: 'ENUM',
  name,
  enumValues: values.map((v) => ({ name: v })),
});

const listArgs = [
  arg('filter', { kind: 'INPUT_OBJECT', name: 'BookFilter', ofType: null }),
  arg('limit', scalar('Int')),
  arg('offset', scalar('Int')),
  arg('search', scalar('String')),
];

/** A capable, Hippo-like endpoint: pagination, filters, FTS, detail, history, batch write. */
export function capableSchema(
  options: { hippoSchema?: boolean; authorDetail?: boolean } = {},
): IntrospectionSchema {
  const queryFields = [
    field('books', nonNull(list(nonNull(object('Book')))), listArgs),
    field(
      'authors',
      nonNull(list(nonNull(object('Author')))),
      [arg('limit', scalar('Int')), arg('offset', scalar('Int'))],
    ),
    // Singular detail field (R3.7) — the preferred detail path for books.
    field('book', object('Book'), [arg('id', nonNull(scalar('ID')))]),
    // Entity change history (R3.7).
    field('entityHistory', nonNull(list(nonNull(object('HistoryEntry')))), [
      arg('entityId', nonNull(scalar('ID'))),
    ]),
  ];
  if (options.hippoSchema) {
    queryFields.push(field('hippoSchema', object('HippoSchema')));
  }
  if (options.authorDetail) {
    queryFields.push(field('author', object('Author'), [arg('id', nonNull(scalar('ID')))]));
  }
  const authorFields = [field('id', nonNull(scalar('ID'))), field('name', scalar('String'))];
  if (options.authorDetail) {
    authorFields.push(field('books', list(nonNull(object('Book')))));
  }
  return {
    queryType: { name: 'Query' },
    mutationType: { name: 'Mutation' },
    types: [
      objectType('Query', queryFields),
      objectType('Mutation', [field('batchPut', object('BatchResult'))]),
      inputObjectType('BookFilter', [
        arg('format', enumRef('BookFormat')),
        arg('in_print', scalar('Boolean')),
        arg('author', scalar('ID')),
        arg('title', scalar('String')), // plain text — not an equality facet
        arg('or', list(nonNull({ kind: 'INPUT_OBJECT', name: 'BookFilter', ofType: null }))),
      ]),
      objectType('HistoryEntry', [
        field('timestamp', nonNull(scalar('String'))),
        field('action', scalar('String')),
        field('actor', scalar('String')),
      ]),
      objectType('Book', [
        field('id', nonNull(scalar('ID'))),
        field('title', nonNull(scalar('String'))),
        field('published_on', scalar('Date')),
        field('page_count', scalar('Int')),
        field('in_print', scalar('Boolean')),
        field('format', enumRef('BookFormat')),
        field('author', object('Author')),
        field('reviews', list(nonNull(object('Review')))),
      ]),
      objectType('Author', authorFields),
      objectType('Review', [field('id', nonNull(scalar('ID'))), field('rating', scalar('Int'))]),
      objectType('HippoSchema', [field('version', scalar('String'))]),
      objectType('BatchResult', [field('ok', scalar('Boolean'))]),
      enumType('BookFormat', ['HARDCOVER', 'PAPERBACK', 'EBOOK']),
    ],
  };
}

/** A bare endpoint: list fields with no args, no mutations, no relationships. */
export function bareSchema(): IntrospectionSchema {
  return {
    queryType: { name: 'Query' },
    mutationType: null,
    types: [
      objectType('Query', [field('things', list(object('Thing')))]),
      objectType('Thing', [field('label', scalar('String'))]),
    ],
  };
}

/**
 * A ScopedDataClient test double: introspection queries get the fixture
 * schema; anything else is answered by `respond` (which also records the
 * query documents + variables it sees).
 */
export interface RecordedQuery {
  document: string;
  variables: Record<string, unknown>;
}

export function fakeClient(
  schema: IntrospectionSchema,
  respond: (
    query: string,
    variables: Record<string, unknown>,
  ) => GraphQLResult<unknown> = () => ({ data: {}, error: null }),
): ScopedDataClient & { queries: string[]; recorded: RecordedQuery[] } {
  const queries: string[] = [];
  const recorded: RecordedQuery[] = [];
  return {
    queries,
    recorded,
    async query<T>(
      document: string,
      variables: Record<string, unknown> = {},
    ): Promise<GraphQLResult<T>> {
      queries.push(document);
      recorded.push({ document, variables });
      if (document.includes('__schema')) {
        const data: IntrospectionData = { __schema: schema };
        return { data: data as T, error: null };
      }
      return respond(document, variables) as GraphQLResult<T>;
    },
  };
}
