import type {
  IntrospectionData,
  IntrospectionField,
  IntrospectionInputValue,
  IntrospectionSchema,
  IntrospectionType,
  TypeRef,
} from '../introspection';
import type { GraphQLResult, ScopedDataClient } from '../scopedClient';
import realIntrospectionJson from './realIntrospection.json';

/**
 * Introspection fixtures for adapter unit tests. Deliberately generic
 * (library-catalog nouns, not any real portal domain — ADR-0002); shaped like
 * a Hippo-style autogenerated read surface: list fields with
 * filter/limit/offset/search args, enum + relationship fields, a batch
 * mutation.
 */

/**
 * The captured `__schema` of a live `hippo serve` (v0.10.3, DataHelix
 * certification fixture schema) — aperture's own INTROSPECTION_QUERY against
 * it. This is the ground truth for the real read shapes (#15) — singular
 * detail fields, `{ items total }` page envelopes, bare-list search twins
 * with required `q`, the generic `[FilterInput!]` + FilterMode filter pair —
 * and the real write shapes: `create<T>(data:)`/`update<T>(id, data:)` plus
 * the `ingestBatch`/`validateBatch` batch unit-of-work.
 */
export const realIntrospection = realIntrospectionJson as unknown as IntrospectionSchema;

export const scalar = (name: string): TypeRef => ({ kind: 'SCALAR', name, ofType: null });
export const enumRef = (name: string): TypeRef => ({ kind: 'ENUM', name, ofType: null });
export const object = (name: string): TypeRef => ({ kind: 'OBJECT', name, ofType: null });
export const nonNull = (ofType: TypeRef): TypeRef => ({ kind: 'NON_NULL', name: null, ofType });
export const list = (ofType: TypeRef): TypeRef => ({ kind: 'LIST', name: null, ofType });

export const field = (
  name: string,
  type: TypeRef,
  args: IntrospectionInputValue[] = [],
): IntrospectionField => ({ name, args, type });

export const arg = (name: string, type: TypeRef): IntrospectionInputValue => ({ name, type });

export const objectType = (name: string, fields: IntrospectionField[]): IntrospectionType => ({
  kind: 'OBJECT',
  name,
  fields,
});

export const inputObjectType = (
  name: string,
  inputFields: IntrospectionInputValue[],
): IntrospectionType => ({ kind: 'INPUT_OBJECT', name, inputFields });

export const enumType = (name: string, values: string[]): IntrospectionType => ({
  kind: 'ENUM',
  name,
  enumValues: values.map((v) => ({ name: v })),
});

const listArgs = [
  arg('filter', { kind: 'INPUT_OBJECT', name: 'BookFilter', ofType: null }),
  arg('limit', scalar('Int')),
  arg('offset', scalar('Int')),
  arg('search', scalar('String')),
];

/** A capable, Hippo-like endpoint: pagination, filters, FTS, detail, history, batch write. */
export function capableSchema(
  options: {
    hippoSchema?: boolean;
    authorDetail?: boolean;
    authorWrite?: boolean;
    /** Adds the Aperture control-plane document collection (Phase 4, N5.4). */
    documents?: boolean;
  } = {},
): IntrospectionSchema {
  const queryFields = [
    field('books', nonNull(list(nonNull(object('Book')))), listArgs),
    field(
      'authors',
      nonNull(list(nonNull(object('Author')))),
      [arg('limit', scalar('Int')), arg('offset', scalar('Int'))],
    ),
    // Singular detail field (R3.7) — the preferred detail path for books.
    field('book', object('Book'), [arg('id', nonNull(scalar('ID')))]),
    // Entity change history (R3.7).
    field('entityHistory', nonNull(list(nonNull(object('HistoryEntry')))), [
      arg('entityId', nonNull(scalar('ID'))),
    ]),
  ];
  if (options.hippoSchema) {
    queryFields.push(field('hippoSchema', object('HippoSchema')));
  }
  if (options.authorDetail) {
    queryFields.push(field('author', object('Author'), [arg('id', nonNull(scalar('ID')))]));
  }
  const authorFields = [field('id', nonNull(scalar('ID'))), field('name', scalar('String'))];
  if (options.authorDetail) {
    authorFields.push(field('books', list(nonNull(object('Book')))));
  }
  const mutationExtras: IntrospectionField[] = [];
  const typeExtras: IntrospectionType[] = [];
  if (options.authorWrite) {
    mutationExtras.push(
      field('createAuthor', object('Author'), [
        arg('input', nonNull({ kind: 'INPUT_OBJECT', name: 'AuthorInput', ofType: null })),
      ]),
    );
    typeExtras.push(inputObjectType('AuthorInput', [arg('name', nonNull(scalar('String')))]));
  }
  const queryExtras: IntrospectionField[] = [];
  if (options.documents) {
    queryExtras.push(
      field('apertureDocuments', nonNull(list(nonNull(object('ApertureDocument')))), [
        arg('filter', { kind: 'INPUT_OBJECT', name: 'ApertureDocumentFilter', ofType: null }),
        arg('limit', scalar('Int')),
        arg('offset', scalar('Int')),
      ]),
    );
    mutationExtras.push(
      field('createApertureDocument', object('ApertureDocument'), [
        arg('input', nonNull({ kind: 'INPUT_OBJECT', name: 'ApertureDocumentInput', ofType: null })),
      ]),
      field('updateApertureDocument', object('ApertureDocument'), [
        arg('id', nonNull(scalar('ID'))),
        arg('input', nonNull({ kind: 'INPUT_OBJECT', name: 'ApertureDocumentUpdateInput', ofType: null })),
      ]),
    );
    typeExtras.push(
      objectType('ApertureDocument', [
        field('id', nonNull(scalar('ID'))),
        field('kind', nonNull(scalar('String'))),
        field('name', nonNull(scalar('String'))),
        field('payload', nonNull(scalar('String'))),
      ]),
      inputObjectType('ApertureDocumentFilter', [
        arg('kind', scalar('String')),
        arg('name', scalar('String')),
      ]),
      inputObjectType('ApertureDocumentInput', [
        arg('kind', nonNull(scalar('String'))),
        arg('name', nonNull(scalar('String'))),
        arg('payload', nonNull(scalar('String'))),
      ]),
      inputObjectType('ApertureDocumentUpdateInput', [
        arg('kind', scalar('String')),
        arg('name', scalar('String')),
        arg('payload', scalar('String')),
      ]),
    );
  }
  return {
    queryType: { name: 'Query' },
    mutationType: { name: 'Mutation' },
    types: [
      objectType('Query', [...queryFields, ...queryExtras]),
      objectType('Mutation', [
        // Batch unit-of-work (Hippo #84, real shape confirmed live — #15):
        // entity list + optional relationships + dry-run, plus a validate twin.
        field('ingestBatch', nonNull(object('BatchWriteGraphQLResult')), [
          arg(
            'entities',
            nonNull(list(nonNull({ kind: 'INPUT_OBJECT', name: 'BatchEntityInput', ofType: null }))),
          ),
          arg(
            'relationships',
            list(nonNull({ kind: 'INPUT_OBJECT', name: 'BatchRelationshipInput', ofType: null })),
          ),
          arg('dryRun', nonNull(scalar('Boolean'))),
        ]),
        field('validateBatch', nonNull(object('BatchValidationGraphQLResult')), [
          arg(
            'entities',
            nonNull(list(nonNull({ kind: 'INPUT_OBJECT', name: 'BatchEntityInput', ofType: null }))),
          ),
        ]),
        // Tier-0 write paths (W4.3): create takes an input; update adds an id.
        field('createBook', object('Book'), [
          arg('input', nonNull({ kind: 'INPUT_OBJECT', name: 'BookInput', ofType: null })),
        ]),
        field('updateBook', object('Book'), [
          arg('id', nonNull(scalar('ID'))),
          arg('input', nonNull({ kind: 'INPUT_OBJECT', name: 'BookUpdateInput', ofType: null })),
        ]),
        ...mutationExtras,
      ]),
      inputObjectType('BookInput', [
        arg('title', nonNull(scalar('String'))),
        arg('published_on', scalar('Date')),
        arg('page_count', scalar('Int')),
        arg('in_print', scalar('Boolean')),
        arg('format', enumRef('BookFormat')),
        arg('author', scalar('ID')),
        arg('tags', list(scalar('String'))), // multivalued — no Tier-0 widget, omitted
      ]),
      inputObjectType('BookUpdateInput', [
        arg('title', scalar('String')),
        arg('published_on', scalar('Date')),
        arg('page_count', scalar('Int')),
        arg('in_print', scalar('Boolean')),
        arg('format', enumRef('BookFormat')),
        arg('author', scalar('ID')),
      ]),
      inputObjectType('BookFilter', [
        arg('format', enumRef('BookFormat')),
        arg('in_print', scalar('Boolean')),
        arg('author', scalar('ID')),
        arg('title', scalar('String')), // plain text — not an equality facet
        arg('or', list(nonNull({ kind: 'INPUT_OBJECT', name: 'BookFilter', ofType: null }))),
      ]),
      objectType('HistoryEntry', [
        field('timestamp', nonNull(scalar('String'))),
        field('action', scalar('String')),
        field('actor', scalar('String')),
      ]),
      inputObjectType('BatchEntityInput', [
        arg('entityType', nonNull(scalar('String'))),
        arg('data', nonNull(scalar('JSON'))),
        arg('operation', nonNull(scalar('String'))), // defaults to "insert" server-side
      ]),
      inputObjectType('BatchRelationshipInput', [
        arg('sourceId', nonNull(scalar('ID'))),
        arg('targetId', nonNull(scalar('ID'))),
        arg('relationshipType', nonNull(scalar('String'))),
        arg('metadata', scalar('JSON')),
      ]),
      objectType('BatchWriteGraphQLResult', [
        field('committed', nonNull(scalar('Boolean'))),
        field('dryRun', nonNull(scalar('Boolean'))),
        field('validation', nonNull(object('BatchValidationGraphQLResult'))),
        field('entities', nonNull(list(nonNull(scalar('JSON'))))),
        field('relationships', nonNull(list(nonNull(scalar('JSON'))))),
      ]),
      objectType('BatchValidationGraphQLResult', [
        field('passed', nonNull(scalar('Boolean'))),
        field('results', nonNull(list(nonNull(object('BatchEntityValidation'))))),
      ]),
      objectType('BatchEntityValidation', [
        field('entityId', scalar('ID')),
        field('passed', nonNull(scalar('Boolean'))),
        field('failures', nonNull(list(nonNull(object('ValidationFailureType'))))),
      ]),
      objectType('ValidationFailureType', [
        field('tier', nonNull(scalar('String'))),
        field('rule', nonNull(scalar('String'))),
        field('message', nonNull(scalar('String'))),
        field('field', scalar('String')),
        field('details', scalar('JSON')),
      ]),
      objectType('Book', [
        field('id', nonNull(scalar('ID'))),
        field('title', nonNull(scalar('String'))),
        field('published_on', scalar('Date')),
        field('page_count', scalar('Int')),
        field('in_print', scalar('Boolean')),
        field('format', enumRef('BookFormat')),
        field('author', object('Author')),
        field('reviews', list(nonNull(object('Review')))),
      ]),
      objectType('Author', authorFields),
      objectType('Review', [field('id', nonNull(scalar('ID'))), field('rating', scalar('Int'))]),
      objectType('HippoSchema', [field('version', scalar('String'))]),
      enumType('BookFormat', ['HARDCOVER', 'PAPERBACK', 'EBOOK']),
      ...typeExtras,
    ],
  };
}

/** A bare endpoint: list fields with no args, no mutations, no relationships. */
export function bareSchema(): IntrospectionSchema {
  return {
    queryType: { name: 'Query' },
    mutationType: null,
    types: [
      objectType('Query', [field('things', list(object('Thing')))]),
      objectType('Thing', [field('label', scalar('String'))]),
    ],
  };
}

/**
 * A ScopedDataClient test double: introspection queries get the fixture
 * schema; anything else is answered by `respond` (which also records the
 * query documents + variables it sees).
 */
export interface RecordedQuery {
  document: string;
  variables: Record<string, unknown>;
}

export function fakeClient(
  schema: IntrospectionSchema,
  respond: (
    query: string,
    variables: Record<string, unknown>,
  ) => GraphQLResult<unknown> = () => ({ data: {}, error: null }),
): ScopedDataClient & { queries: string[]; recorded: RecordedQuery[] } {
  const queries: string[] = [];
  const recorded: RecordedQuery[] = [];
  const handle = <T,>(
    document: string,
    variables: Record<string, unknown>,
  ): GraphQLResult<T> => {
    queries.push(document);
    recorded.push({ document, variables });
    if (document.includes('__schema')) {
      const data: IntrospectionData = { __schema: schema };
      return { data: data as T, error: null };
    }
    return respond(document, variables) as GraphQLResult<T>;
  };
  return {
    queries,
    recorded,
    async query<T>(document: string, variables: Record<string, unknown> = {}) {
      return handle<T>(document, variables);
    },
    async mutate<T>(document: string, variables: Record<string, unknown> = {}) {
      return handle<T>(document, variables);
    },
  };
}
