import type {
  IntrospectionData,
  IntrospectionField,
  IntrospectionInputValue,
  IntrospectionSchema,
  IntrospectionType,
  TypeRef,
} from '../introspection';
import type { GraphQLResult, ScopedDataClient } from '../scopedClient';

/**
 * Introspection fixtures for adapter unit tests. Deliberately generic
 * (library-catalog nouns, not any real portal domain — ADR-0002); shaped like
 * a Hippo-style autogenerated read surface: list fields with
 * filter/limit/offset/search args, enum + relationship fields, a batch
 * mutation.
 */

export const scalar = (name: string): TypeRef => ({ kind: 'SCALAR', name, ofType: null });
export const enumRef = (name: string): TypeRef => ({ kind: 'ENUM', name, ofType: null });
export const object = (name: string): TypeRef => ({ kind: 'OBJECT', name, ofType: null });
export const nonNull = (ofType: TypeRef): TypeRef => ({ kind: 'NON_NULL', name: null, ofType });
export const list = (ofType: TypeRef): TypeRef => ({ kind: 'LIST', name: null, ofType });

export const field = (
  name: string,
  type: TypeRef,
  args: IntrospectionInputValue[] = [],
): IntrospectionField => ({ name, args, type });

export const arg = (name: string, type: TypeRef): IntrospectionInputValue => ({ name, type });

export const objectType = (name: string, fields: IntrospectionField[]): IntrospectionType => ({
  kind: 'OBJECT',
  name,
  fields,
});

export const enumType = (name: string, values: string[]): IntrospectionType => ({
  kind: 'ENUM',
  name,
  enumValues: values.map((v) => ({ name: v })),
});

const listArgs = [
  arg('filter', { kind: 'INPUT_OBJECT', name: 'BookFilter', ofType: null }),
  arg('limit', scalar('Int')),
  arg('offset', scalar('Int')),
  arg('search', scalar('String')),
];

/** A capable, Hippo-like endpoint: pagination, filters, FTS, batch write. */
export function capableSchema(options: { hippoSchema?: boolean } = {}): IntrospectionSchema {
  const queryFields = [
    field('books', nonNull(list(nonNull(object('Book')))), listArgs),
    field(
      'authors',
      nonNull(list(nonNull(object('Author')))),
      [arg('limit', scalar('Int')), arg('offset', scalar('Int'))],
    ),
  ];
  if (options.hippoSchema) {
    queryFields.push(field('hippoSchema', object('HippoSchema')));
  }
  return {
    queryType: { name: 'Query' },
    mutationType: { name: 'Mutation' },
    types: [
      objectType('Query', queryFields),
      objectType('Mutation', [field('batchPut', object('BatchResult'))]),
      objectType('Book', [
        field('id', nonNull(scalar('ID'))),
        field('title', nonNull(scalar('String'))),
        field('published_on', scalar('Date')),
        field('page_count', scalar('Int')),
        field('in_print', scalar('Boolean')),
        field('format', enumRef('BookFormat')),
        field('author', object('Author')),
        field('reviews', list(nonNull(object('Review')))),
      ]),
      objectType('Author', [
        field('id', nonNull(scalar('ID'))),
        field('name', scalar('String')),
      ]),
      objectType('Review', [field('id', nonNull(scalar('ID'))), field('rating', scalar('Int'))]),
      objectType('HippoSchema', [field('version', scalar('String'))]),
      objectType('BatchResult', [field('ok', scalar('Boolean'))]),
      enumType('BookFormat', ['HARDCOVER', 'PAPERBACK', 'EBOOK']),
    ],
  };
}

/** A bare endpoint: list fields with no args, no mutations, no relationships. */
export function bareSchema(): IntrospectionSchema {
  return {
    queryType: { name: 'Query' },
    mutationType: null,
    types: [
      objectType('Query', [field('things', list(object('Thing')))]),
      objectType('Thing', [field('label', scalar('String'))]),
    ],
  };
}

/**
 * A ScopedDataClient test double: introspection queries get the fixture
 * schema; anything else is answered by `respond` (which also records the
 * query documents it sees).
 */
export function fakeClient(
  schema: IntrospectionSchema,
  respond: (query: string) => GraphQLResult<unknown> = () => ({ data: {}, error: null }),
): ScopedDataClient & { queries: string[] } {
  const queries: string[] = [];
  return {
    queries,
    async query<T>(document: string): Promise<GraphQLResult<T>> {
      queries.push(document);
      if (document.includes('__schema')) {
        const data: IntrospectionData = { __schema: schema };
        return { data: data as T, error: null };
      }
      return respond(document) as GraphQLResult<T>;
    },
  };
}
